#!/usr/bin/env python3
"""generate_waypoints.py
Generate optimised Crazyflie waypoints using the pdSTL planner.

Usage:
    python generate_waypoints.py [--fan {0,6,12,18}] [--plot]

Output:
    Overwrites components/opt_waypoints.py with a WAYPOINTS list.
    T+1=11 tuples (x, y, z), including the initial position.
"""

from __future__ import annotations

import argparse
import datetime
import math
import pathlib
import sys

import numpy as np
import torch

# ── ensure project root is on sys.path ──────────────────────────────────────
HERE = pathlib.Path(__file__).resolve().parent  # .../probabilistic_stl/
PROJ = HERE.parent.parent.parent.parent  # .../irobot  (project root)
sys.path.insert(0, str(PROJ))

from pdstl.base import BeliefTrajectory

from irobot.src.projects.probabilistic_stl.planning.dynamics import SingleIntegrator
from irobot.src.projects.probabilistic_stl.planning.environment import Environment
from irobot.src.projects.probabilistic_stl.planning.planner import (
    ProbabilisticSTLPlanner,
    TorchGaussianBelief,
)

# ── Measured constants ───────────────────────────────────────────────────────
T = 10  # planning horizon (number of control steps)
DT = 0.693  # mean inter-waypoint time [s] — confirmed from det. fan00 runs (mean=0.693, std=0.072)
U_MAX = 0.44  # max inter-waypoint speed [m/s] — measured from det. fan00 runs (mean=0.43, max=0.44)
Z_HEIGHT = 0.2  # flight height [m]

Q_STD_PER_FAN: dict[int, float] = {
    2: 0.001,
    6: 0.006,
    12: 0.020,
    16: 0.050,
}

# Initial belief — measured values
X0_MEAN = torch.tensor([0.0, -1.5], dtype=torch.float32)
X0_COV = torch.diag(torch.tensor([1e-2, 1e-2], dtype=torch.float32))


# ── Helper functions ─────────────────────────────────────────────────────────


def _sine_waypoints() -> list[tuple[float, float, float]]:
    """10-waypoint sine path (y ∈ [-1.5, 0.65]), unscaled commanded coordinates."""
    start_0 = 1.5
    y_pos = np.linspace(-start_0, 0.65, 10)
    x_pos = 0.5 * np.sin(np.pi * y_pos / start_0)
    return [(float(x), float(y), Z_HEIGHT) for x, y in zip(x_pos, y_pos)]


def _build_environment() -> Environment:
    # Obstacle bounds converted from environment.py (inches → metres):
    # x_m = x_in * 0.0254,  y_m = y_in * 0.0254 - 1.5
    env = Environment()
    env.add_obstacle(x_range=[-0.165, 0.165], y_range=[-1.144, -0.941])  # OBS-1 (red)
    env.add_obstacle(x_range=[-0.432, -0.102], y_range=[-0.179, 0.049])  # OBS-2 (blue)
    env.add_obstacle(x_range=[0.114, 0.343], y_range=[-0.611, -0.421])  # OBS-3 (green)
    env.set_goal(x_range=[-0.30, 0.30], y_range=[0.10, 0.30])
    return env


def _sine_init_guess() -> torch.Tensor:
    """Convert sine waypoints to T=10 velocity controls for warm-starting."""
    wps = np.array(_sine_waypoints())  # (10, 3) — includes x0 at index 0
    vels = np.diff(wps[:, :2], axis=0) / DT  # (9, 2)
    vels = np.vstack([vels, [[0.0, 0.0]]])  # (10, 2) — pad final step with zero
    return torch.tensor(vels, dtype=torch.float32)


def _evaluate_rho(planner: ProbabilisticSTLPlanner, init_u: torch.Tensor) -> float:
    """Evaluate STL P(sat) for a given control sequence without optimising."""
    u_norm = torch.clamp(init_u / planner.dyn.u_max, -0.99, 0.99)
    v = 0.5 * torch.log((1 + u_norm) / (1 - u_norm))
    with torch.no_grad():
        mean_trace, cov_trace = planner.dyn(v, X0_MEAN, X0_COV)
        beliefs = [TorchGaussianBelief(mean_trace[:, t, :], cov_trace[:, t]) for t in range(T + 1)]
        phi = planner.env.get_specification(T)
        return phi(BeliefTrajectory(beliefs))[0, 0, 0].item()


def _write_waypoints(
    path: pathlib.Path,
    waypoints: list[tuple[float, float, float]],
    rho_before: float,
    rho_after: float,
    alpha: float,
    fan: int,
) -> None:
    ts = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%S+00:00')
    lines = [
        '# Auto-generated by generate_waypoints.py — do not edit by hand.',
        f'# generated={ts}  rho_before={rho_before:.4f}  rho_after={rho_after:.4f}  alpha={alpha}  fan={fan}',
        '',
        'WAYPOINTS: list[tuple[float, float, float]] = [',
    ]
    for x, y, z in waypoints:
        lines.append(f'    ({x:.6f}, {y:.6f}, {z}),')
    lines += [']', '']
    path.write_text('\n'.join(lines))


# ── Plot ─────────────────────────────────────────────────────────────────────


def _plot(
    env: Environment,
    sine_wps: np.ndarray,
    opt_xy: np.ndarray,
    opt_cov: np.ndarray,
) -> None:
    import matplotlib.patches as patches
    import matplotlib.pyplot as plt
    from matplotlib.patches import Ellipse

    fig, axes = plt.subplots(1, 2, figsize=(14, 7))
    for ax, (path_xy, title, draw_ellipses) in zip(
        axes,
        [
            (sine_wps[:, :2], 'Before (Sine Path)', False),
            (opt_xy, 'After (pdSTL Optimised)', True),
        ],
    ):
        ax.set_title(title)
        ax.set_aspect('equal')
        ax.set_xlim(-1.2, 1.2)
        ax.set_ylim(-1.8, 1.0)
        ax.grid(True, alpha=0.3)

        for obs in env.obstacles:
            ox, oy = obs['x'], obs['y']
            ax.add_patch(
                patches.Rectangle(
                    (ox[0], oy[0]),
                    ox[1] - ox[0],
                    oy[1] - oy[0],
                    facecolor='red',
                    alpha=0.4,
                    edgecolor='darkred',
                )
            )

        if env.goal:
            gx, gy = env.goal['x'], env.goal['y']
            ax.add_patch(
                patches.Rectangle(
                    (gx[0], gy[0]),
                    gx[1] - gx[0],
                    gy[1] - gy[0],
                    facecolor='green',
                    alpha=0.3,
                    edgecolor='darkgreen',
                )
            )

        ax.plot(path_xy[:, 0], path_xy[:, 1], 'b.-', lw=2, ms=8)
        ax.plot(path_xy[0, 0], path_xy[0, 1], 'go', ms=10, label='start')
        ax.plot(path_xy[-1, 0], path_xy[-1, 1], 'rs', ms=10, label='end')

        if draw_ellipses:
            for t in range(len(opt_xy)):
                cov_t = opt_cov[t]
                vals, vecs = np.linalg.eigh(cov_t)
                angle = math.degrees(math.atan2(*vecs[:, -1][::-1]))
                w, h = 2 * 2 * np.sqrt(np.maximum(vals, 0))
                el = Ellipse(
                    xy=opt_xy[t],
                    width=w,
                    height=h,
                    angle=angle,
                    edgecolor='blue',
                    facecolor='none',
                    alpha=0.5,
                    lw=0.8,
                )
                ax.add_patch(el)

        ax.legend()

    plt.tight_layout()
    out = HERE / 'waypoints_comparison.png'
    plt.savefig(out, dpi=150)
    print(f'Plot saved to {out}')
    plt.show()


# ── Main ─────────────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(description='Generate optimised Crazyflie waypoints via pdSTL')
    parser.add_argument(
        '--fan',
        type=int,
        default=2,
        choices=[2, 6, 12, 16],
        help='Fan speed level; selects process noise Q for planner',
    )
    parser.add_argument('--plot', action='store_true', help='Show before/after path plot')
    args = parser.parse_args()

    alpha = 0.90

    dynamics = SingleIntegrator(dt=DT, u_max=U_MAX, q_std=Q_STD_PER_FAN[args.fan])
    env = _build_environment()
    planner = ProbabilisticSTLPlanner(
        dynamics,
        env,
        T,
        config={
            'w_phi': 20.0,
            'w_dist': 5.0,
            'w_obs': 5.0,
            'alpha': alpha,
            'max_iters': 1000,
            'lr': 0.02,
        },
    )

    init_u = _sine_init_guess()

    rho_before = _evaluate_rho(planner, init_u)
    print(f'rho_before (sine path): {rho_before:.4f}')

    best_mean, best_cov, _best_u, best_p, _history = planner.solve(
        X0_MEAN,
        X0_COV,
        init_guess=init_u,
        verbose=True,
    )
    print(f'rho_after  (optimised):  {best_p:.4f}')

    # best_mean: [1, T+1, 2] → (T+1, 2)
    positions_xy = best_mean.squeeze(0).cpu().numpy()
    waypoints = [(float(x), float(y), Z_HEIGHT) for x, y in positions_xy]

    out_path = HERE / 'components' / 'opt_waypoints.py'
    _write_waypoints(out_path, waypoints, rho_before, best_p, alpha, args.fan)
    print(f'Written {len(waypoints)} waypoints to {out_path}')

    if args.plot:
        sine_wps = np.array(_sine_waypoints())
        _plot(env, sine_wps, positions_xy, best_cov.squeeze(0).cpu().numpy())


if __name__ == '__main__':
    main()
