# cake_config.py — generated by calibrate_arm.py
# Do not edit by hand. Re-run calibrate_arm.py to update.

import numpy as np

# ── Gripper ───────────────────────────────────────────────────────────
# These are NOT written by calibrate_arm.py — adjust manually to fit the handle.
GRIPPER_OPEN   = 0.035  # m — wide enough to slide over the knife handle
GRIPPER_CLOSED = 0.0   # m — firm grip; increase if the knife slips during cut

# ── Joint-space waypoints ─────────────────────────────────────────────
KNIFE_HOVER_JOINTS   = np.array([-0.24052, 1.40631, 1.62985, -0.11578, -0.00134, -0.00210, 0.00489])
KNIFE_GRIP_JOINTS    = np.array([-0.25349, 1.40059, 1.33650, -0.01774, -0.00095, -0.00248, 0.00489])
CAKE_APPROACH_JOINTS = np.array([-0.26074, 1.59552, 1.34184, 0.04788, -0.06123, -0.00210, 0.00489])

# ── Knife rest (Cartesian) ────────────────────────────────────────────
KNIFE_REST_X   = 0.44067
KNIFE_REST_Y   = -0.10783
KNIFE_REST_Z   = 0.38721
KNIFE_REST_ORI = np.array([-0.01512, -0.10698, -0.23907])

# ── Cake geometry ─────────────────────────────────────────────────────
CAKE_CX = 0.51098
CAKE_CY = -0.12462
CAKE_HL = 0.13335   # half of 10.5"
CAKE_HW = 0.10795   # half of  8.5"

# ── Heights ───────────────────────────────────────────────────────────
PLATFORM_Z = 0.14016
CAKE_Z_TOP = 0.17028
CAKE_Z_CUT = 0.14516
Z_APPROACH = 0.31243

# ── Knife cutting orientation ─────────────────────────────────────────
KNIFE_ORI = np.array([0.03096, 0.20369, -0.19859])
