# Calibration helper for cake_cut.py
#
# Run this, move the arm to each prompted position, press Enter to capture.
# At the end it writes cake_config.py automatically — no copy-paste needed.
#
# Usage:
#   conda run -n trossen_ai_env python calibrate_arm.py

import time
from pathlib import Path
import trossen_arm
from cake_config import GRIPPER_OPEN, GRIPPER_CLOSED

CONFIG_PATH = Path(__file__).parent / "cake_config.py"

POSES = [
    ("KNIFE_HOVER",   "Gripper open, hovering ~4-5 cm ABOVE the knife handle"),
    ("KNIFE_GRIP",    "Gripper at handle height — where it will close on the handle"),
    ("CAKE_APPROACH", "Knife gripped, blade vertical, hovering above CAKE CENTRE\n"
                      "   at safe clearance height (10-15 cm above cake top)"),
    ("CAKE_TOP",      "Knife tip just touching the TOP SURFACE of the cake"),
    ("CAKE_CUT",      "Knife fully through cake, tip just above platform surface"),
]

def capture(arm: trossen_arm.TrossenArmDriver, label: str, description: str) -> dict:
    print(f"\n── {label} ─────────────────────────────────────────")
    print(f"   {description}")
    print("   Move the arm to this position, then press Enter...")
    while True:
        input()
        cur_joints = list(arm.get_all_positions())
        cur_cart   = list(arm.get_cartesian_positions())

        arm.set_all_modes(trossen_arm.Mode.position)
        arm.set_all_positions(cur_joints, 0.1, True)
        arm.set_gripper_position(GRIPPER_CLOSED, 0.5, True)

        arm.set_all_modes(trossen_arm.Mode.external_effort)
        arm.set_all_external_efforts([0.0] * 7, 0.0, False)

        print(f"   Cartesian : {[round(v, 5) for v in cur_cart]}")
        print(f"   Joints    : {[round(v, 5) for v in cur_joints]}")
        confirm = input("   Capture these values? [Y/n]: ").strip().lower()
        if confirm in ("", "y", "yes"):
            return {"cart": cur_cart, "joints": cur_joints}
        print("   OK — move the arm again and press Enter when ready.")

def fmt_array(values: list) -> str:
    return "np.array([" + ", ".join(f"{v:.5f}" for v in values) + "])"

def write_config(captured: dict) -> None:
    kh = captured["KNIFE_HOVER"]
    kg = captured["KNIFE_GRIP"]
    ca = captured["CAKE_APPROACH"]
    ct = captured["CAKE_TOP"]
    cc = captured["CAKE_CUT"]

    gripper_open   = 0.035
    gripper_closed = 0.000
    if CONFIG_PATH.exists():
        for line in CONFIG_PATH.read_text().splitlines():
            if line.startswith("GRIPPER_OPEN"):
                gripper_open   = float(line.split("=")[1].split("#")[0].strip())
            if line.startswith("GRIPPER_CLOSED"):
                gripper_closed = float(line.split("=")[1].split("#")[0].strip())

    content = f"""\
# cake_config.py — generated by calibrate_arm.py
# Do not edit by hand. Re-run calibrate_arm.py to update.

import numpy as np

# ── Gripper ───────────────────────────────────────────────────────────
# These are NOT written by calibrate_arm.py — adjust manually to fit the handle.
GRIPPER_OPEN   = {gripper_open}   # m — wide enough to slide over the knife handle
GRIPPER_CLOSED = {gripper_closed}   # m — firm grip; increase if the knife slips during cut

# ── Joint-space waypoints ─────────────────────────────────────────────
KNIFE_HOVER_JOINTS   = {fmt_array(kh['joints'])}
KNIFE_GRIP_JOINTS    = {fmt_array(kg['joints'])}
CAKE_APPROACH_JOINTS = {fmt_array(ca['joints'])}

# ── Knife rest (Cartesian) ────────────────────────────────────────────
KNIFE_REST_X   = {kh['cart'][0]:.5f}
KNIFE_REST_Y   = {kh['cart'][1]:.5f}
KNIFE_REST_Z   = {kg['cart'][2]:.5f}
KNIFE_REST_ORI = {fmt_array(kh['cart'][3:])}

# ── Cake geometry ─────────────────────────────────────────────────────
CAKE_CX = {ca['cart'][0]:.5f}
CAKE_CY = {ca['cart'][1]:.5f}
CAKE_HL = 0.13335   # half of 10.5"
CAKE_HW = 0.10795   # half of  8.5"

# ── Heights ───────────────────────────────────────────────────────────
PLATFORM_Z = {cc['cart'][2] - 0.005:.5f}
CAKE_Z_TOP = {ct['cart'][2]:.5f}
CAKE_Z_CUT = {cc['cart'][2]:.5f}
Z_APPROACH = {ca['cart'][2]:.5f}

# ── Knife cutting orientation ─────────────────────────────────────────
KNIFE_ORI = {fmt_array(ca['cart'][3:])}
"""
    CONFIG_PATH.write_text(content)
    print(f"\nSaved to {CONFIG_PATH}")


if __name__ == '__main__':
    arm = trossen_arm.TrossenArmDriver()
    arm.configure(
        trossen_arm.Model.wxai_v0,
        trossen_arm.StandardEndEffector.wxai_v0_follower,
        "192.168.1.3",
        True,
    )

    print("── Home position ──────────────────────────────────────")
    print(f"   Cartesian : {[round(v, 5) for v in arm.get_cartesian_positions()]}")
    print(f"   Joints    : {[round(v, 5) for v in arm.get_all_positions()]}")

    print("\nOpening gripper — place knife in gripper, then press Enter...")
    arm.set_all_modes(trossen_arm.Mode.position)
    arm.set_gripper_position(GRIPPER_OPEN, 1.5, True)
    input()
    arm.set_gripper_position(GRIPPER_CLOSED, 1.5, True)
    time.sleep(2)
    arm.set_gripper_position(GRIPPER_CLOSED, 1.5, True)
    time.sleep(2)
    print("Knife gripped.")

    print("\nEnabling gravity compensation — move slowly, knife re-grips on each Enter.")
    arm.set_all_modes(trossen_arm.Mode.external_effort)
    arm.set_all_external_efforts([0.0] * 7, 0.0, False)

    captured = {}
    for label, description in POSES:
        captured[label] = capture(arm, label, description)

    write_config(captured)
    print("Done. Run algorithms/cake_cut.py to execute the cut sequence.")
