# Trossen Cake Cutting — project configuration
#
# Edit values here before running. cake_config.py is auto-generated by
# calibrate_arm.py and should not be edited by hand.

# ── Hardware ──────────────────────────────────────────────────────────
ARM_IP = "192.168.1.3"   # follower arm used for autonomous cutting

# ── Gripper ───────────────────────────────────────────────────────────
# Adjust to fit the Farberware knife handle. cake_config.py reads these back
# so it doesn't overwrite them on recalibration.
GRIPPER_OPEN   = 0.035   # m — wide enough to slide over the handle
GRIPPER_CLOSED = 0.0     # m — firm grip; increase by 0.002 if knife slips

# ── Cake geometry (rectangular) ───────────────────────────────────────
CAKE_HALF_LENGTH = 0.13335   # m — half of 10.5"
CAKE_HALF_WIDTH  = 0.10795   # m — half of 8.5"

# ── Round cake ────────────────────────────────────────────────────────
CAKE_DIAMETER = 6.5 * 0.0254   # m — 6.5" in metres

# ── Teleoperation ─────────────────────────────────────────────────────
TELEOP_LEADER_IP   = "192.168.1.4"
TELEOP_FOLLOWER_IP = "192.168.1.5"
TELEOP_DURATION    = 30        # seconds
FORCE_FEEDBACK_GAIN = 0.1

# ── All calibrated constants (Cartesian waypoints, joint waypoints, heights)
# are stored in cake_config.py, written automatically by calibrate_arm.py.
from irobot.src.projects.trossen_cake.cake_config import *  # noqa: F401, F403
